### ISSUE TITLE
Using the system ??

### ISSUE THREAD

**Issue by softfoot** [robsonsmartins/usbflashprog#1]
Sorry to leave this as an "issue" but I couldnt find any other way to contact someone re this intreaging project.
I am very interested in building this but cannot find any user docs (probably my fault).
Given that it plugs into a PC via USB - what software is run on the PC ??
I assume it may be just a serial emulator in which case where can I find the commands and arguments ??
If its a program on the PC - where can I find it ??
All the very best,
Dave

**Comment by robsonsmartins** [comment]
Thanks for contacting Dave.

I updated the project status information in the [README](https://github.com/robsonsmartins/usbflashprog/blob/main/README.md).

As you can see, this project is under development, and at its current status, there is still no PC software or user documentation.

Currently, the effort is in validating the hardware specification, through a prototype, and developing the firmware for it.

If you have knowledge of Electronic Engineering or Firmware (C/C++) or Software (C++/Qt) Development, and want to contribute to the project, you can read the [CONTRIBUTING](https://github.com/robsonsmartins/usbflashprog/blob/main/CONTRIBUTING.md) file.

Regards,
Robson Martins
