### ISSUE TITLE
AM29F support

### ISSUE THREAD

**Issue by red2211** [robsonsmartins/usbflashprog#3]
Hi, if I understood correctly, this programmer is able to r/w to AM28F flash. So my question is, can this programmer r/w an AM29F flash?
As I read the datasheet for AM28F and AM29F they are both similar in terms of r/w but the only difference I have noticed is voltage levels: AM28F has 12v, and AM29F has 5v.

**Comment by robsonsmartins** [comment]
Yes, 29F flash will be supported. I remember that this project is in progress, and there is still a lot to add for version 1.0 to be released. I have currently frozen the software implementations to work on the PCB design, as the hardware prototype has been validated.
